package aboutNew;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import org.json.JSONArray;
import org.json.JSONObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class GeminiService {

    private static final Logger logger = LoggerFactory.getLogger(GeminiService.class);
    private static final HttpClient client = HttpClient.newHttpClient();

    public static String askGemini(String prompt) {
        int attempts = Rotator.getKeyCount();
        for (int attempt = 0; attempt < attempts; attempt++) {
            String apiKey = Rotator.getCurrentKey();
            if (apiKey == null) {
                logger.error("[GeminiService] No API keys loaded in ApiKeyRotator!");
                return "Error: No API keys loaded in ApiKeyRotator!";
            }

            try {
                final String API_URL = "https://generativelanguage.googleapis.com/v1beta/models/" + Rotator.getModel() + ":generateContent";
                // Build the JSON payload
                JSONObject part = new JSONObject().put("text", prompt);
                JSONObject content = new JSONObject().put("parts", new JSONArray().put(part));
                JSONObject requestBody = new JSONObject().put("contents", new JSONArray().put(content));

                String requestUrl = API_URL + "?key=" + apiKey;

                HttpRequest request = HttpRequest.newBuilder()
                        .uri(URI.create(requestUrl))
                        .header("Content-Type", "application/json")
                        .POST(HttpRequest.BodyPublishers.ofString(requestBody.toString(), StandardCharsets.UTF_8))
                        .build();

                // HttpRequest requestMock = HttpRequest.newBuilder()
                //         .uri(URI.create("https://httpbin.org/status/503")) 
                //         .build();

                HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

                if (response.statusCode() == 200) {
                    JSONObject jsonResponse = new JSONObject(response.body());
                    JSONArray candidates = jsonResponse.getJSONArray("candidates");
                    if (candidates.length() > 0) {
                        JSONObject candidate = candidates.getJSONObject(0);
                        JSONObject candidateContent = candidate.getJSONObject("content");
                        JSONArray parts = candidateContent.getJSONArray("parts");
                        if (parts.length() > 0) {
                            return parts.getJSONObject(0).getString("text");
                        }
                    }
                    return "Error: No response generated by Gemini.";
                } else if (response.statusCode() == 429 || response.statusCode() == 403) {
                    logger.warn("[GeminiService] API Key exhausted (Status: {}). Rotating key and retrying...", response.statusCode());
                    Rotator.rotateKey();
                } else if (response.statusCode() == 503) {
                    logger.warn("[GeminiService] Model under too many requests ATM (Status: {})", response.statusCode());
                    logger.info("Rotating Model from {} and signaling frontend to retry...", Rotator.getModel());
                    Rotator.rotateModel();
                    logger.info("Model rotated to {}", Rotator.getModel());
                    return "RETRY_503";
                } else {
                    logger.error("[GeminiService] Gemini LLM API returned status code {}: {}", response.statusCode(), response.body());
                    return "Error: Gemini API returned status code " + response.statusCode();
                }
            } catch (Exception e) {
                logger.error("[GeminiService] Error calling Gemini LLM API:", e);
                return "Error: " + e.getMessage();
            }
        }
        logger.error("[GeminiService] All API keys have been exhausted for this request.");
        return "Error: All API keys have been exhausted.";
    }
}
